#!/usr/bin/env bash
# Needs bash 3.2, POSIX tools and base64
# theme.css and the snippets are generated and never committed: Obsidian installs
# them from a release's assets, which the release workflow builds from the tagged sources,
# so a vendored source that moves needs no second commit to follow it. Colours come only
# from vendor/; the template src/ddlc.css names them as var(--ddlc-*) and never holds a
# literal colour. Each colour is emitted twice, as hex and as an "r, g, b" triple, since
# Obsidian still reads a few of its own variables as triples. The stickers are a snippet
# of their own, so the theme the directory serves carries no official artwork. base64 is
# not POSIX, but GNU and BSD both read stdin and wrap their output, which tr undoes
set -euo pipefail

usage() {
  cat <<'EOF'
generate.sh — render theme.css from the vendored DDLC palette, its dark base16 scheme,
the shared DDLC roles, the vendored Lucide icons and the theme template, and the optional
snippets:
ddlc-stickers.css with the club's stickers, ddlc-still.css that stops the background and
ddlc-nerd.css that draws code with the Nerd Fonts icons

  generate.sh build [-o DIR]   write the theme and the snippets (default: beside this script)

  -o DIR   the directory build writes theme.css, ddlc-stickers.css, ddlc-still.css and
           ddlc-nerd.css into

Nothing here reaches the network
Exit 0 done, 1 when a source is missing or malformed, 2 on a usage error
EOF
}

fail() { # the thing asked about is wrong
  printf 'generate.sh: %s\n' "$1" >&2
  exit 1
}

die() { # the request itself is wrong
  printf 'generate.sh: %s\n' "$1" >&2
  exit 2
}

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PALETTE="$HERE/vendor/palette.css"
TEMPLATE="$HERE/src/ddlc.css"
# The roles every DDLC surface shares, from ddlc-themes: the template maps them onto
# Obsidian's variables and its own selectors
TOKENS="$HERE/vendor/ddlc-tokens.css"
BASE16="$HERE/vendor/base16-ddlc-dark.yaml"
ICONS="$HERE/vendor/lucide"
ICON_LICENSE="$ICONS/LICENSE"
# The theme's faces, from ddlc-themes: Nunito for prose, Departure Mono for code
FONTS="$HERE/vendor/fonts"
STICKERS="$HERE/assets"
STICKER_TEMPLATE="$HERE/src/stickers.css"
STILL_TEMPLATE="$HERE/src/still.css"
# Departure Mono with the Nerd Fonts icons, from ddlc-themes, and its licences: the font's,
# and the icon sets' in the archive's README
NERD="$HERE/vendor/nerd"
NERD_TEMPLATE="$HERE/src/nerd.css"
WORK=$(mktemp -d "${TMPDIR:-/tmp}/ddlc-obsidian.XXXXXX")
trap 'rm -rf "$WORK"' EXIT

render() {
  local line name hex count=0
  [[ -f "$PALETTE" ]] || fail "missing $PALETTE"
  [[ -f "$TEMPLATE" ]] || fail "missing $TEMPLATE"
  [[ -f "$TOKENS" ]] || fail "missing $TOKENS"
  [[ -f "$ICON_LICENSE" ]] || fail "missing $ICON_LICENSE"
  # *\/* is a literal */, which would close the notice's comment early
  case "$(cat "$ICON_LICENSE")" in *'*/'*) fail "$ICON_LICENSE holds */ and cannot sit in a comment" ;; esac
  printf '/* Generated by generate.sh from vendor/ and src/ddlc.css — do not edit */\n\n'
  # The icons are embedded below, and their licence asks for its notice in every copy
  printf '/* The task and copy icons are Lucide icons, https://lucide.dev\n\n'
  cat "$ICON_LICENSE"
  printf '*/\n\n'
  render_font_notices
  render_fonts
  # On the root, not the body: the vendored roles below are declared there and read these
  # colours, and a var() resolves on the element that declares it
  printf ':root {\n'
  while IFS= read -r line; do
    case "$line" in
      *--ddlc-*:*'#'*) ;;
      *) continue ;;
    esac
    name=${line#*--ddlc-}
    name=${name%%:*}
    hex=${line#*'#'}
    hex=${hex%%;*}
    [[ "$hex" =~ ^[0-9A-Fa-f]{6}$ ]] || fail "not a six-digit colour for $name: $hex"
    printf '  --ddlc-%s: #%s;\n' "$name" "$hex"
    printf '  --ddlc-%s-rgb: %d, %d, %d;\n' "$name" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
    count=$((count + 1))
  done <"$PALETTE"
  ((count > 0)) || fail "no --ddlc-* colours in $PALETTE"
  render_base16
  render_icons
  printf '}\n\n'
  cat "$TOKENS"
  printf '\n'
  cat "$TEMPLATE"
}

# The dark base16 slots, the same ones ddlc.nvim paints syntax with, so code reads
# alike in both. The template uses them for every code block, which is dark on both sides
render_base16() {
  local line slot hex count=0
  [[ -f "$BASE16" ]] || fail "missing $BASE16"
  while IFS= read -r line; do
    case "$line" in
      *base0[[:xdigit:]]:*'#'*) ;;
      *) continue ;;
    esac
    slot=${line#*base}
    slot=${slot%%:*}
    hex=${line#*'#'}
    hex=${hex%%'"'*}
    [[ "$hex" =~ ^[0-9A-Fa-f]{6}$ ]] || fail "not a six-digit colour for base$slot: $hex"
    printf '  --ddlc-base%s: #%s;\n' "$slot" "$hex"
    count=$((count + 1))
  done <"$BASE16"
  ((count == 16)) || fail "expected 16 base16 slots in $BASE16, found $count"
}

# The fonts' licences travel with the fonts embedded below, as the SIL OFL asks
render_font_notices() {
  local license
  for license in "$FONTS/Nunito-LICENSE.txt" "$FONTS/DepartureMono-LICENSE.txt"; do
    [[ -f "$license" ]] || fail "missing $license"
    case "$(cat "$license")" in *'*/'*) fail "$license holds */ and cannot sit in a comment" ;; esac
    printf '/* %s, embedded below\n\n' "$(basename -- "$license" -LICENSE.txt)"
    cat "$license"
    printf '*/\n\n'
  done
}

# Each face as a data URI under a name of its own, so the theme draws with its own copy
# and never with a different version a system has installed
render_fonts() {
  local file
  for file in Nunito.woff2 Nunito-Italic.woff2 DepartureMono-Regular.woff2; do
    [[ -f "$FONTS/$file" ]] || fail "missing $FONTS/$file"
  done
  font_face "DDLC Nunito" "200 1000" normal "$FONTS/Nunito.woff2"
  font_face "DDLC Nunito" "200 1000" italic "$FONTS/Nunito-Italic.woff2"
  font_face "DDLC Departure Mono" 400 normal "$FONTS/DepartureMono-Regular.woff2"
}

font_face() { # <family> <weight> <style> <woff2>
  printf '@font-face {\n  font-family: "%s";\n  font-weight: %s;\n  font-style: %s;\n' "$1" "$2" "$3"
  printf '  src: url("data:font/woff2;base64,%s") format("woff2");\n}\n\n' "$(base64 <"$4" | tr -d '\n')"
}

# Each vendored Lucide icon as a data URI for a mask, so the template colours it with
# a palette token. Only the characters a url() cannot carry raw are escaped
render_icons() {
  local svg name data count=0
  for svg in "$ICONS"/*.svg; do
    [[ -f "$svg" ]] || continue
    name=$(basename -- "$svg" .svg)
    # tr swaps the double quotes for single ones: a quoted ${//} replacement differs in 3.2
    data=$(tr '"\n' "' " <"$svg" | tr -s ' ')
    data=${data//'#'/%23}
    data=${data//'<'/%3C}
    data=${data//'>'/%3E}
    printf '  --ddlc-icon-%s: url("data:image/svg+xml,%s");\n' "$name" "$data"
    count=$((count + 1))
  done
  ((count > 0)) || fail "no icons in $ICONS"
}

# The snippet: every girl's calm and excited frame as a data URI, one variable per file,
# named after the file, --ddlc-sayori-sticker-calm for sayori-sticker-calm.png
render_stickers() {
  local png name count=0
  [[ -f "$STICKER_TEMPLATE" ]] || fail "missing $STICKER_TEMPLATE"
  printf '/* Generated by generate.sh from assets/ and src/stickers.css — do not edit\n'
  printf '   An optional snippet for the DDLC theme. The stickers are Team Salvato'"'"'s, used\n'
  printf '   as non-commercial fan content; see ASSETS.md in the theme'"'"'s repository */\n\n'
  printf 'body {\n'
  for png in "$STICKERS"/*-sticker-calm.png "$STICKERS"/*-sticker-excited.png; do
    [[ -f "$png" ]] || continue
    name=$(basename -- "$png" .png)
    printf '  --ddlc-%s: url("data:image/png;base64,%s");\n' "$name" "$(base64 <"$png" | tr -d '\n')"
    count=$((count + 1))
  done
  ((count == 8)) || fail "expected 8 sticker frames in $STICKERS, found $count"
  printf '}\n\n'
  cat "$STICKER_TEMPLATE"
}

# The snippet that stops the background's drift, a switch the theme reads
render_still() {
  [[ -f "$STILL_TEMPLATE" ]] || fail "missing $STILL_TEMPLATE"
  printf '/* Generated by generate.sh from src/still.css — do not edit\n'
  printf '   An optional snippet for the DDLC theme */\n\n'
  cat "$STILL_TEMPLATE"
}

# The snippet that draws code with the Nerd Fonts icons. It carries its own face, so it
# works under any theme, and the notices of the font and of every icon set in it
render_nerd() {
  local file
  [[ -f "$NERD_TEMPLATE" ]] || fail "missing $NERD_TEMPLATE"
  for file in DepartureMonoNerdFontMono-Regular.woff2 DepartureMonoNerdFont-LICENSE.txt DepartureMonoNerdFont-README.md; do
    [[ -f "$NERD/$file" ]] || fail "missing $NERD/$file"
  done
  for file in "$NERD/DepartureMonoNerdFont-LICENSE.txt" "$NERD/DepartureMonoNerdFont-README.md"; do
    case "$(cat "$file")" in *'*/'*) fail "$file holds */ and cannot sit in a comment" ;; esac
  done
  printf '/* Generated by generate.sh from vendor/nerd/ and src/nerd.css — do not edit\n'
  printf '   An optional snippet, for the DDLC theme or any other */\n\n'
  printf '/* DepartureMono Nerd Font Mono, embedded below. The font'"'"'s licence:\n\n'
  cat "$NERD/DepartureMonoNerdFont-LICENSE.txt"
  printf '*/\n\n/* The Nerd Fonts README that comes with it, with the licence of each icon set:\n\n'
  cat "$NERD/DepartureMonoNerdFont-README.md"
  printf '*/\n\n'
  font_face "DDLC Departure Mono Nerd" 400 normal "$NERD/DepartureMonoNerdFontMono-Regular.woff2"
  cat "$NERD_TEMPLATE"
}

cmd_build() {
  local out="$HERE"
  while (($#)); do
    case "$1" in
      -o)
        (($# >= 2)) || die "-o needs a directory"
        out="$2"
        shift 2
        ;;
      -*) die "no such flag: $1" ;;
      *) die "unexpected argument: $1" ;;
    esac
  done
  [[ -d "$out" ]] || die "$out is not a directory"
  # All rendered whole first, so a failed render never leaves a half-written file behind
  render >"$WORK/theme.css"
  render_stickers >"$WORK/ddlc-stickers.css"
  render_still >"$WORK/ddlc-still.css"
  render_nerd >"$WORK/ddlc-nerd.css"
  # cat rather than cp: a copy would keep mktemp's owner-only mode
  cat "$WORK/theme.css" >"$out/theme.css"
  cat "$WORK/ddlc-stickers.css" >"$out/ddlc-stickers.css"
  cat "$WORK/ddlc-still.css" >"$out/ddlc-still.css"
  cat "$WORK/ddlc-nerd.css" >"$out/ddlc-nerd.css"
}

cmd="${1:-}"
(($# == 0)) || shift
case "$cmd" in
  build) cmd_build "$@" ;;
  -h | --help | help) usage ;;
  '')
    usage >&2
    exit 2
    ;;
  *)
    printf 'generate.sh: no such subcommand: %s\n\n' "$cmd" >&2
    usage >&2
    exit 2
    ;;
esac
