#!/usr/bin/env bash
# Needs bash 3.2, POSIX tools and base64
# theme.css and ddlc-stickers.css are generated and never committed: Obsidian installs
# them from a release's assets, which the release workflow builds from the tagged sources,
# so a vendored source that moves needs no second commit to follow it. Colours come only
# from vendor/; the template src/ddlc.css names them as var(--ddlc-*) and never holds a
# literal colour. Each colour is emitted twice, as hex and as an "r, g, b" triple, since
# Obsidian still reads a few of its own variables as triples. The stickers are a snippet
# of their own, so the theme the directory serves carries no official artwork. base64 is
# not POSIX, but GNU and BSD both read stdin and wrap their output, which tr undoes
set -euo pipefail

usage() {
  cat <<'EOF'
generate.sh — render theme.css from the vendored DDLC palette, its dark base16 scheme,
the vendored Lucide icons and the theme template, and ddlc-stickers.css, the optional
snippet with the club's stickers

  generate.sh build [-o DIR]   write both files (default: beside this script)

  -o DIR   the directory build writes theme.css and ddlc-stickers.css into

Nothing here reaches the network
Exit 0 done, 1 when a source is missing or malformed, 2 on a usage error
EOF
}

fail() { # the thing asked about is wrong
  printf 'generate.sh: %s\n' "$1" >&2
  exit 1
}

die() { # the request itself is wrong
  printf 'generate.sh: %s\n' "$1" >&2
  exit 2
}

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PALETTE="$HERE/vendor/palette.css"
TEMPLATE="$HERE/src/ddlc.css"
BASE16="$HERE/vendor/base16-ddlc-dark.yaml"
ICONS="$HERE/vendor/lucide"
ICON_LICENSE="$ICONS/LICENSE"
STICKERS="$HERE/assets"
STICKER_TEMPLATE="$HERE/src/stickers.css"
WORK=$(mktemp -d "${TMPDIR:-/tmp}/ddlc-obsidian.XXXXXX")
trap 'rm -rf "$WORK"' EXIT

render() {
  local line name hex count=0
  [[ -f "$PALETTE" ]] || fail "missing $PALETTE"
  [[ -f "$TEMPLATE" ]] || fail "missing $TEMPLATE"
  [[ -f "$ICON_LICENSE" ]] || fail "missing $ICON_LICENSE"
  # *\/* is a literal */, which would close the notice's comment early
  case "$(cat "$ICON_LICENSE")" in *'*/'*) fail "$ICON_LICENSE holds */ and cannot sit in a comment" ;; esac
  printf '/* Generated by generate.sh from vendor/ and src/ddlc.css — do not edit */\n\n'
  # The icons are embedded below, and their licence asks for its notice in every copy
  printf '/* The task and copy icons are Lucide icons, https://lucide.dev\n\n'
  cat "$ICON_LICENSE"
  printf '*/\n\n'
  printf 'body {\n'
  while IFS= read -r line; do
    case "$line" in
      *--ddlc-*:*'#'*) ;;
      *) continue ;;
    esac
    name=${line#*--ddlc-}
    name=${name%%:*}
    hex=${line#*'#'}
    hex=${hex%%;*}
    [[ "$hex" =~ ^[0-9A-Fa-f]{6}$ ]] || fail "not a six-digit colour for $name: $hex"
    printf '  --ddlc-%s: #%s;\n' "$name" "$hex"
    printf '  --ddlc-%s-rgb: %d, %d, %d;\n' "$name" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
    count=$((count + 1))
  done <"$PALETTE"
  ((count > 0)) || fail "no --ddlc-* colours in $PALETTE"
  render_base16
  render_icons
  printf '}\n\n'
  cat "$TEMPLATE"
}

# The dark base16 slots, the same ones ddlc.nvim paints syntax with, so code reads
# alike in both. The template uses them for every code block, which is dark on both sides
render_base16() {
  local line slot hex count=0
  [[ -f "$BASE16" ]] || fail "missing $BASE16"
  while IFS= read -r line; do
    case "$line" in
      *base0[[:xdigit:]]:*'#'*) ;;
      *) continue ;;
    esac
    slot=${line#*base}
    slot=${slot%%:*}
    hex=${line#*'#'}
    hex=${hex%%'"'*}
    [[ "$hex" =~ ^[0-9A-Fa-f]{6}$ ]] || fail "not a six-digit colour for base$slot: $hex"
    printf '  --ddlc-base%s: #%s;\n' "$slot" "$hex"
    count=$((count + 1))
  done <"$BASE16"
  ((count == 16)) || fail "expected 16 base16 slots in $BASE16, found $count"
}

# Each vendored Lucide icon as a data URI for a mask, so the template colours it with
# a palette token. Only the characters a url() cannot carry raw are escaped
render_icons() {
  local svg name data count=0
  for svg in "$ICONS"/*.svg; do
    [[ -f "$svg" ]] || continue
    name=$(basename -- "$svg" .svg)
    # tr swaps the double quotes for single ones: a quoted ${//} replacement differs in 3.2
    data=$(tr '"\n' "' " <"$svg" | tr -s ' ')
    data=${data//'#'/%23}
    data=${data//'<'/%3C}
    data=${data//'>'/%3E}
    printf '  --ddlc-icon-%s: url("data:image/svg+xml,%s");\n' "$name" "$data"
    count=$((count + 1))
  done
  ((count > 0)) || fail "no icons in $ICONS"
}

# The snippet: every girl's calm and excited frame as a data URI, one variable per file,
# named after the file, --ddlc-sayori-sticker-calm for sayori-sticker-calm.png
render_stickers() {
  local png name count=0
  [[ -f "$STICKER_TEMPLATE" ]] || fail "missing $STICKER_TEMPLATE"
  printf '/* Generated by generate.sh from assets/ and src/stickers.css — do not edit\n'
  printf '   An optional snippet for the DDLC theme. The stickers are Team Salvato'"'"'s, used\n'
  printf '   as non-commercial fan content; see ASSETS.md in the theme'"'"'s repository */\n\n'
  printf 'body {\n'
  for png in "$STICKERS"/*-sticker-calm.png "$STICKERS"/*-sticker-excited.png; do
    [[ -f "$png" ]] || continue
    name=$(basename -- "$png" .png)
    printf '  --ddlc-%s: url("data:image/png;base64,%s");\n' "$name" "$(base64 <"$png" | tr -d '\n')"
    count=$((count + 1))
  done
  ((count == 8)) || fail "expected 8 sticker frames in $STICKERS, found $count"
  printf '}\n\n'
  cat "$STICKER_TEMPLATE"
}

cmd_build() {
  local out="$HERE"
  while (($#)); do
    case "$1" in
      -o)
        (($# >= 2)) || die "-o needs a directory"
        out="$2"
        shift 2
        ;;
      -*) die "no such flag: $1" ;;
      *) die "unexpected argument: $1" ;;
    esac
  done
  [[ -d "$out" ]] || die "$out is not a directory"
  # Both rendered whole first, so a failed render never leaves a half-written file behind
  render >"$WORK/theme.css"
  render_stickers >"$WORK/ddlc-stickers.css"
  # cat rather than cp: a copy would keep mktemp's owner-only mode
  cat "$WORK/theme.css" >"$out/theme.css"
  cat "$WORK/ddlc-stickers.css" >"$out/ddlc-stickers.css"
}

cmd="${1:-}"
(($# == 0)) || shift
case "$cmd" in
  build) cmd_build "$@" ;;
  -h | --help | help) usage ;;
  '')
    usage >&2
    exit 2
    ;;
  *)
    printf 'generate.sh: no such subcommand: %s\n\n' "$cmd" >&2
    usage >&2
    exit 2
    ;;
esac
